context:
  version: "2.5.1"

package:
  name: jiti
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/jiti/-/jiti-${{ version }}.tgz
  sha256: 0db910dfc06a0486db75a56fd4fe8b298b3d20cfd2dc25cd1bf208117aae38c7

build:
  number: 0
  noarch: generic

requirements:
  build:
    - nodejs
  run:
    - nodejs

tests:
  - script:
      - jiti 2>&1 | grep -q "Usage: "jiti <path> \\[...arguments\\]\""

about:
  license: MIT
  license_file: LICENSE
  summary: Runtime Typescript and ESM support for Node.js
  homepage: https://github.com/unjs/jiti
  repository: https://github.com/unjs/jiti

extra:
  recipe-maintainers:
    - danielnachun
